### ISSUE TITLE
Permission System

### ISSUE THREAD

**Issue by LokeYourLord** [discordapp/airhornbot#10]
Hi. I would like to recommend some way of managing who can use !airhorn and the other commands, and who can not. The Mee6 bot has this kind of system, where you can configure the perms for who can use Moderator permissions by adding the permitted roles to the list of allowed roles. This would be handy too for the Airhorn Solutions bot, as i don't exactly like people that come once onto the server, to use the Airhorn bot, especially when they end up spamming it, which is really annoying. I want them first be able to use it when i add them to a specific rank, or if i use the XP/Level system from the Mee6 bot.

**Comment by BlazyDoesDev** [comment]
+1

**Comment by b1naryth1ef** [comment]
Airhorn is a fun project we used to demo the capabilities of the Discord API. If your interested, feel free to fork and extend it with whatever you want.
