### ISSUE TITLE
bot ignoring commands after failed payload delivery

### ISSUE THREAD

**Issue by EntranceJew** [discordapp/airhornbot#14]
There were some connectivity issues with voice the other night and airhornbot was summoned in the midst of it. Airhornbot was stuck trying to make some noise in a voice channel but ended up sticking around indefinitely because it seems like he couldn't deliver the voice payload. 

The solution I was given to deal with the connectivity issue was to switch server regions temporarily. While all the users had their voice communications restored after doing this, airhorn bot stuck around a little longer and then disconnected. Attempting to `!airhorn` after this resulted in airhornbot ignoring the command entirely. Even kicking and letting airhornbot rejoin the channel didn't fix anything.

**Comment by An63rX3r0** [comment]
I have the same issue. So sad that I can't irhorn on my server... :(

**Comment by SaiZa** [comment]
This is a critical issue!! The Airhorn Solutions bot seems to ignore ANY command from now and then, like he's stuck in an infinite loop or something.

Tried to kick/ban, remove/add permissions, server change, changing his name back and again, force into loop breaks (like invalid actions) to break loop state. No reaction at all.

It's like Airhorn Solutions Bot is mad at us. :/

**Comment by Spidersouris** [comment]
I have the same issue.

**Comment by OOrks** [comment]
Simple solution.

1. Create a voice channel.
2. Drag Bot into the new channel.
3. Delete Channel
4. Profit $$$???
5. Yeah the bot will then make airhorns.

**Comment by SaiZa** [comment]
@OOrks : You can't drag the bot in a channel unless he's in one already.

The bot started re-working after a couple of days for me anyway.

**Comment by alexholliz** [comment]
I am having the same issue, AirhornBot just sits in the user list, and no amount of coaxing will encourage him to join a voice channel. I tried default permissions, and I tried adding roles that give him access to all of our text and voice channels, and nada. 

I've tried kicking him, deleting his role, then readding him, and still no dice.
He works in my other servers, but in my friend group's main chat, he's a goner. :(

**Comment by medcat** [comment]
I'm having this same issue now.  The airhorn bot refuses to make any sound; kicking it and having it rejoin does nothing.  Once someone puts `!airhorn` in chat, it joins the voice chat and sits there for a while.  I've tried changing the regions, deleting the voice channels he was in, banning the airhorn bot (ok, maybe that wasn't for diagnostic purposes...), and pretty much everything I can think of.  I'm not sure what's causing this.

**Comment by glassa** [comment]
Having issue right now
Im guessing its a server side thing, since it started within minutes of medcat getting the bug.
For reference, airhorn has all privileges, has been kicked and reinvited, regions changed, and he's currently sitting in his own special voice channel.
I have to say, that might be a worthwhile sound for him to make occasionally. Just silence for like... 30 seconds, then go off.

**Comment by SeiZaNex** [comment]
Look. For whoever reads this.
The issue CANNOT be worked around.
Only solution is to WAIT, for the bot to reset / timeout itself from ignoring commands. 

There is even a comment line saying that airhorn bot will get "tired" at some point
