### ISSUE TITLE
Dead bot occurs when spamming !airhorn.

### ISSUE THREAD

**Issue by jaffarfiree** [discordapp/airhornbot#19]
I have no idea how this happened, but the airhorn bot will no longer join voice chat when calling !airhorn after a night of repeated calling.

**Comment by DavidJFelix** [comment]
Also having this issue. I've checked permissions, totally removed all traces of the bot, re-added it and still nothing. This airhorn has squeaked its last.

**Comment by SaiZa** [comment]
#14 Similar issue?
