### ISSUE TITLE
discord.ShardID undefined

### ISSUE THREAD

**Issue by Jared5595** [discordapp/airhornbot#25]
Issue:
# github.com/hammerandchisel/airhornbot/cmd/bot

src/github.com/hammerandchisel/airhornbot/cmd/bot/bot.go:709: discord.ShardID undefined (type *discordgo.Session has no field or method ShardID)
src/github.com/hammerandchisel/airhornbot/cmd/bot/bot.go:710: discord.ShardCount undefined (type *discordgo.Session has no field or method ShardCount)
src/github.com/hammerandchisel/airhornbot/cmd/bot/bot.go:712: discord.ShardCount undefined (type *discordgo.Session has no field or method ShardCount)
src/github.com/hammerandchisel/airhornbot/cmd/bot/bot.go:713: discord.ShardCount undefined (type *discordgo.Session has no field or method ShardCount)

Upon running "go get github.com/hammerandchisel/airhornbot/cmd/bot"

Using Go 1.6.2

**Comment by mttrs** [comment]
I think it is due to the compatibility between discordgos master and develop branch. Master doesn't, but develop branch has the variables.

https://github.com/bwmarrin/discordgo/blob/master/structs.go#L40
https://github.com/bwmarrin/discordgo/blob/develop/structs.go#L42

**Comment by ThomasCork** [comment]
Master branch has those variables now, can this issue be closed?
