### ISSUE TITLE
3 Issues on bomb command

### ISSUE THREAD

**Issue by DouglasAntunes** [discordapp/airhornbot#27]
- If the bot don't find the channel of the user to play sound, results in crash. See https://github.com/hammerandchisel/airhornbot/blob/master/cmd/bot/bot.go#L563-L564
- If you pass a negative number to parameter "number of times", results in crash.
- If you pass a non-int (string or float) value the bot only responds :ok_hand: on chat, enter on voice chat, play nothing and leave.

**Comment by LucaVazz** [comment]
Er, how exactly are you supposed to use this command...?

**Comment by DouglasAntunes** [comment]
@LucaVazz Type on chat: @MentionTheBot bomb @PersonToBomb NumberOfTimes

**Comment by noname6464** [comment]
Somehow its not working for me. I tried it a few times. Any ideas?
