### ISSUE TITLE
401 Unauthorized when Playing Sound

### ISSUE THREAD

**Issue by asswolf** [discordapp/airhornbot#30]
This command generates as soon as I play a sound using !airhorn:
2016/09/23 01:06:26 HTTP 401 Unauthorized, {"code": 0, "message": "401: Unauthorized"}
2016/09/23 01:06:27 [DG0] wsapi.go:524:onVoiceServerUpdate() onVoiceServerUpdate voice.open, Did not receive voice Session ID in time.
ERRO[0045] Failed to play sound 
error=Timeout waiting for voice.

The bot will enter the voice channel, make no noise, then get stuck in the channel.   It has the correct channel ID / userID / Guild ID.  The bot has proper permissions to join voice and use voice.

**Comment by b1naryth1ef** [comment]
https://github.com/hammerandchisel/airhornbot/pull/29

**Comment by asswolf** [comment]
I made this modification to my bot.go file and restarted the bot, but after trying to !airhorn, I get the same issue.  Is there something I should be doing besides replacing the file and re-starting the bot?

**Comment by mjohn314** [comment]
After making the change, reinstall. 

> go install github.com/hammerandchisel/airhornbot/cmd/bot
