### ISSUE TITLE
Bot not working anymore?

### ISSUE THREAD

**Issue by BrokenSilence** [discordapp/airhornbot#33]
Bot doesnt recognize the command anymore.. 
Its online, but its like a dead person. Does nothing.

Did something change?

**Comment by stephenrubio94** [comment]
For me, it's offline and won't respond to commands.  I've tried kicking and re-adding and it doesn't seem to work.

**Comment by deanio97** [comment]
The bot seems to be totally offline for me... if it had a Windows binary I'd compile it but there are only Linux ones from what I can see in the source code...

**Comment by gblikas** [comment]
I am not sure if this matters but [on their website](https://discordapp.com/developers/docs/intro) the do say "Now that the noise has subsided"... 

I am not sure if this is suppose to be literal. But, I am having the same problem as you guys.

**Comment by NaabKing** [comment]
seems dead for me too, for quite some time... like few feeks actually =/

**Comment by gblikas** [comment]
@NaabKing So, I got it to work! 

I am going to be honest, I don't know why this work, nor have any reason to think that it should work as a solution. But, I followed the instructions found [here](https://github.com/hammerandchisel/airhornbot): 
`go get github.com/hammerandchisel/airhornbot/cmd/bot
go install github.com/hammerandchisel/airhornbot/cmd/bot`
After that, I ran the local host instance on the same webpage. 

This really should NOT have mattered at all.

**Comment by NaabKing** [comment]
@gblikas 
sorry, but where do i type that in? :) CMD? Cuz i tried and it said "go is not a valid command", something like that :D

**Comment by Ancro** [comment]
You need to be running the bot on your own server to do that. According to [discordapp on Twitter](https://twitter.com/discordapp/status/792128801002127362), the guy who built this should have fixed it already. Can you try to add it again and see if that works?

**Comment by NaabKing** [comment]
the weird thing is, it does work if i create a completly new server and add the bot there, BUT if i add it to a server that it previously worked without a problem, it simply does not work anymore... =/ But it did before... no idea what's going on, because "gravebot" works without any problems for example.

**Comment by Ancro** [comment]
Have you kicked it before using airhorn.solutions again?

**Comment by NaabKing** [comment]
yep, it simply does not work (i didn't change anything and it did work few weeks ago) =/ when i add it back to a server, the bot doesn't even type "AIRHORN BOT READY FOR HORNING. TYPE !AIRHORN WHILE IN A VOICE CHANNEL TO ACTIVATE".

**Comment by gblikas** [comment]
@NaabKing So, as far a public bots are concerned, you should  _not_ have to run your own server. However, I have had no success with the (supposedly supported) Discord server for Airhorn. So, instead I run the bot on my own machine. 

To do so, you need to set up a (Go) Golang environment and run the server on your own PC. That is a little to involved for a comment.

**Comment by Blogshot** [comment]
It seems the bot is not funtional at this point, except one is willing to install it on their own server. I tried - but there is no sufficient documentation for an easy installation whatsoever!

After downloading the bot via go, I can CD into the "bin/"-Directory and, after copying the audio files from src, run the bot.
Well, now I have the bot up and running, but I can't find a hint on what ports to open in my firewall and how to actually add the bot to any discord!

Not to mention the missing documentation on parameters or where to find the data.
bot -r "localhost:6379" -t "MY_BOT_ACCOUNT_TOKEN" -o OWNER_ID

Please, include a step-by-step tutorial in the readme.
