### ISSUE TITLE
line 464: cannot convert nil to type bool

### ISSUE THREAD

**Issue by Jodh** [discordapp/airhornbot#35]
installing the bot gives the following error on line 464 in bot.go file.

> cannot convert nil to type bool 
>
`
	if event.Guild.Unavailable != nil {
		return
	}
`

**Comment by Victor-Sun** [comment]
I'm getting this error too.

`
/usr/share/go/src/github.com/hammerandchisel/airhornbot/cmd/bot/bot.go:464: cannot convert nil to type bool
`

**Comment by vaaski** [comment]
Getting the same error.
`\go\src\github.com\hammerandchisel\airhornbot\cmd\bot\bot.go:464: cannot convert nil to type bool`

**Comment by calebjessie** [comment]
I'm getting this error as well when trying to install on my Ubuntu server.

**Comment by aacalfa** [comment]
Same error here. No fix yet?

**Comment by calebjessie** [comment]
@aacalfa I ended up finding this comment by OGRepeatingDigits after some searching - https://www.reddit.com/r/discordapp/comments/5v3sgq/the_airhorn_bot_problems/ddzt0oz/

Within this comment it's stated that you should just remove "!= nil" on line 464. So it becomes:
`if event.Guild.Unavailable { ... }`

I found that this actually works. Although I'm not sure how it affects the rest of the code, if at all. With this change I was able to get airhorn up and running on my server.

Also, I noticed when running `go install github.com/...` bot.exe is actually created within `C:\Users\yourusername\go\src\github.com\hammerandchisel\` and `C:\Users\yourusername\go\bin`

Or if you're on a server, `GOPATH/bin` or `GOPATH/src/github.com/hammerandchisel/`

**Comment by Jannify** [comment]
Here is a fix:
https://github.com/Jannify/Airhorn-Fix-
Use at your own risk...
Just a private repository, not from Hammer and Chisel...
