### ISSUE TITLE
Airhorn noises lagging

### ISSUE THREAD

**Issue by MulverineX** [discordapp/airhornbot#39]
Every about 3 times we use the bot the airhorn sound gets choppy/laggy.

**Comment by filipegatti** [comment]
For a few days already the bot noises are lagging.

**Comment by Zofc** [comment]
This is still an issue; I've yet to hear the bot sound properly. Is it pushing in slices, is there a way I can preload the entire sound file that buffers?

**Comment by thesmokedawg** [comment]
I'm having this issue on our server. The bot works fine on a friend's server, but lags on ours. Any ideas? Ive tried voice regions/ kicking inviting etc.

**Comment by Rafava** [comment]
Having same issues, any fix to this?
