### ISSUE TITLE
Bot stuck on voice channel. Crashed?

### ISSUE THREAD

**Issue by BrokenSilence** [discordapp/airhornbot#43]
Can you please restart the bot, its stuck on the voice channel and does not respost to any command.

Thank you.

**Comment by Sebastien-M** [comment]
Same thing for me :)

**Comment by TNTUP** [comment]
Happened on a friend's discord, I've typed !airhorn and it plays the airhorn then another !airhorn, it joins... but nothing plays and gets stuck in the voice channel

**Comment by calebjessie** [comment]
I've experience the bot getting stuck in voice chats many times.
The latest occurrence happened when two users entered a voice command at the same time.
Could this be the reason for this bug?
Just trying to see if we can get a fix going for this.
