### ISSUE TITLE
Airhorn Solutions bot is Offline

### ISSUE THREAD

**Issue by RScopio** [discordapp/airhornbot#46]
I can't solve my problems which require airhorns. We have tried removing and adding him multiple times but it seems he is out of gas.

**Comment by unixfy** [comment]
Are you running this on your local computer? From what I am getting, this needs to be hosted on a remote server (for 24/7 uptime and for a routed IP).

**Comment by RScopio** [comment]
The bot worked normally by just inviting to our discord server via: https://airhorn.solutions/
Are you saying that at least 1 person needs to be hosting the bot on a server for it to work? Just trying to understand how this works.

**Comment by unixfy** [comment]
I'm  not entirely sure either, the description is quite vague. From my point of understanding, yes, somebody needs to host the bot on their own server.

**Comment by RScopio** [comment]
Interesting. It seemed to work with no server setup for a time. We just invited the bot and it worked. Maybe just 1 person in the world needs to host the bot? I'm unsure. I'll go through the server setup tonight and find out.

**Comment by bwmarrin** [comment]
Nah, it's hosted already.  So you just invite it, and it should work.  However, it may be down sometimes :)  I suspect it'll get fixed eventually...  However, you can host it yourself if you want.

**Comment by Epsynus** [comment]
Bot is still offline, any updates on this?

**Comment by farrellse18** [comment]
Mine is offline too?
I really need help.
It says to run a command, but I have no idea how and where?
