### ISSUE TITLE
Issue installing Web Server

### ISSUE THREAD

**Issue by demonicpagan** [discordapp/airhornbot#9]
I am following the README for installing things on my linux machine and when it comes to installing the webserver portion of the bot, I am having issues and I can't figure out what I'm missing to proceed.

The README says to install the webserver run `go install github.com/hammerandchisel/airhornbot` and I am returned with the following:
`dlennon@debianLinux:~$ go install github.com/hammerandchisel/airhornbot
can't load package: package github.com/hammerandchisel/airhornbot: no buildable Go source files in /home/dlennon/work/src/github.com/hammerandchisel/airhornbot`

I alter that command to be `go install github.com/hammerandchisel/airhornbot/cmd/webserver` just like I was installing the bot and I am presented with:
`work/src/github.com/hammerandchisel/airhornbot/cmd/webserver/web.go:9:2: cannot find package "github.com/antage/eventsource" in any of:
        /usr/local/go/src/github.com/antage/eventsource (from $GOROOT)
        /home/dlennon/work/src/github.com/antage/eventsource (from $GOPATH)
work/src/github.com/hammerandchisel/airhornbot/cmd/webserver/web.go:11:2: cannot find package "github.com/gorilla/handlers" in any of:
        /usr/local/go/src/github.com/gorilla/handlers (from $GOROOT)
        /home/dlennon/work/src/github.com/gorilla/handlers (from $GOPATH)
work/src/github.com/hammerandchisel/airhornbot/cmd/webserver/web.go:12:2: cannot find package "github.com/gorilla/sessions" in any of:
        /usr/local/go/src/github.com/gorilla/sessions (from $GOROOT)
        /home/dlennon/work/src/github.com/gorilla/sessions (from $GOPATH)
work/src/github.com/hammerandchisel/airhornbot/cmd/webserver/web.go:13:2: cannot find package "golang.org/x/oauth2" in any of:
        /usr/local/go/src/golang.org/x/oauth2 (from $GOROOT)
        /home/dlennon/work/src/golang.org/x/oauth2 (from $GOPATH)`

I have installed Redis. I guess I am misreading the whole README for installation.

**Comment by iopred** [comment]
```
go get github.com/hammerandchisel/airhornbot/cmd/bot
go install github.com/hammerandchisel/airhornbot/cmd/bot
```

**Comment by demonicpagan** [comment]
I did perform those operations before even looking at the web server.

**Comment by iopred** [comment]
Please try again, if it can't find the packages listed, it's because you
installed `hammerandchisel/airhornbot`
not `hammerandchisel/airhornbot/cmd/bot`

**Comment by demonicpagan** [comment]
README needs to be updated to install the webserver run `go install hammerandchisel/airhornbot/cmd/webserver` cd to directory where the src folder lives, for me `~/work/src` and navigate to `github.com/hammerandchisel/airhornbot` and then run `make static`

I was able to install the webserver going that route.

**Comment by DerfOh** [comment]
:+1:
I'm having the same problem. I was trying to build a list command into my fork but had to stop because I couldn't seem to get things to build.

I'll give the fix @demonicpagan mentioned a shot tonight.

**Comment by radiodrag** [comment]
still doesn't works to that day, even the new readme file make it worse :\

**Comment by Nuggetslug** [comment]
do a series of "go get" for each error:
`go get github.com\antage\eventsource`
`go get github.com\gorilla\handlers`
`go get github.com\gorilla\sessions`
`go get golang.org\x\oauth2`
you may have to change the direction of the slashes
